version: "3.9"
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-task-manager
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: task-manager
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: basededatos
      MYSQL_PASSWORD: basededatos
    volumes:
      - './mysql:/var/lib/mysql'
